export const POSTERS = [
    "1 (1).png",
    "1.png",
    "10.png",
    "11.png",
    "12.png",
    "13.png",
    "14.png",
    "15.png",
    "16.png",
    "17.png",
    "18.png",
    "19.png",
    "2 (1).png",
    "2.png",
    "20.png",
    "21.png",
    "22.png",
    "23.png",
    "24.png",
    "25.png",
    "26.png",
    "27.png",
    "28.png",
    "29.png",
    "3 (1).png",
    "3.png",
    "30.png",
    "4 (1).png",
    "4.png",
    "5 (1).png",
    "5.png",
    "6 (1).png",
    "6.png",
    "7 (1).png",
    "7.png",
    "8 (1).png",
    "8.png",
    "9.png",
    "Beige and Black Minimalist Fashion Store Logo.png",
    "CXO MEETUP.jpg",
    "Frame 2 (1).png",
    "Frame 2 (2).png",
    "Frame 3 (1).png",
    "Frame 4 (1).png",
    "Frame 6 (1).png",
    "Gemini_Generated_Image_tih0wqtih0wqtih0.png",
    "INTRO TO STZ Benefits and Issues in the IT Sector of Faiselabad & the Way Forward WEDNESDAY, 5TH NOV. 2025  630 PM 630 PM 800 PM.png",
    "National University of Modern Languages (Faisalabad Campus) INDOOR SPORTS FEST.png",
    "Orange and Black Illustrated Halloween Party Poster.png",
    "Sports Fest Intramurals Banner in Blue and Neon Green Illustrative Style(1).png",
    "Untitled (Your Story)(1).png",
    "Untitled design(18).png",
    "Untitled design(19).png",
    "Untitled design(20).png",
    "Untitled design(22).png",
    "_sarautomation.png",
    "annual dinner.png",
    "httpsportals.numl.edu.pk AdmissionPortalLogin.png",
    "jvolabs.png",
    "osama(1).png",
    "sarzone automation.png",
    "sir naeem.png",
    "sports fest.png",
    "wxpo.pdf"
].filter(f => !f.endsWith(".pdf"));
