const RAW_ARCHIVED_POSTERS = [
    "1 (1).webp",
    "1.webp",
    "10.webp",
    "11.webp",
    "12.webp",
    "13.webp",
    "14.webp",
    "15.webp",
    "16.webp",
    "17.webp",
    "18.webp",
    "19.webp",
    "2 (1).webp",
    "2.webp",
    "20.webp",
    "21.webp",
    "22.webp",
    "23.webp",
    "24.webp",
    "25.webp",
    "26.webp",
    "27.webp",
    "28.webp",
    "29.webp",
    "3 (1).webp",
    "3.webp",
    "30.webp",
    "4 (1).webp",
    "4.webp",
    "5 (1).webp",
    "5.webp",
    "6 (1).webp",
    "6.webp",
    "7 (1).webp",
    "7.webp",
    "8 (1).webp",
    "8.webp",
    "9.webp",
    "Beige and Black Minimalist Fashion Store Logo.webp",
    "CXO MEETUP.webp",
    "Frame 2 (1).webp",
    "Frame 2 (2).webp",
    "Frame 3 (1).webp",
    "Frame 4 (1).webp",
    "Frame 6 (1).webp",
    "Gemini_Generated_Image_tih0wqtih0wqtih0.webp",
    "INTRO TO STZ Benefits and Issues in the IT Sector of Faiselabad & the Way Forward WEDNESDAY, 5TH NOV. 2025  630 PM 630 PM 800 PM.webp",
    "National University of Modern Languages (Faisalabad Campus) INDOOR SPORTS FEST.webp",
    "Orange and Black Illustrated Halloween Party Poster.webp",
    "Sports Fest Intramurals Banner in Blue and Neon Green Illustrative Style(1).webp",
    "Untitled (Your Story)(1).webp",
    "Untitled design(18).webp",
    "Untitled design(19).webp",
    "Untitled design(20).webp",
    "Untitled design(22).webp",
    "_sarautomation.webp",
    "annual dinner.webp",
    "httpsportals.numl.edu.pk AdmissionPortalLogin.webp",
    "jvolabs.webp",
    "osama(1).webp",
    "sarzone automation.webp",
    "sir naeem.webp",
    "sports fest.webp",
    "wxpo.pdf",
    "ChatGPT Image Jun 3, 2026, 03_35_34 PM.webp",
    "ChatGPT Image Jun 3, 2026, 04_38_18 PM.webp",
    "ChatGPT Image Jun 3, 2026, 04_47_49 PM.webp",
    "ChatGPT Image Jun 3, 2026, 12_30_23 AM.webp"
];

export const ACTIVE_POSTERS: string[] = [
    "1.webp",
    "2.webp",
    "3.webp",
    "4.webp",
    "5.webp",
    "6.webp",
    "7.webp",
    "8.webp",
    "9.webp",
    "10.webp",
    "11.webp",
    "12.webp",
    "13.webp",
    "14.webp",
    "15.webp",
    "16.webp",
    "17.webp",
    "18.webp",
    "19.webp",
    "20.webp",
    "21.webp",
    "22.webp",
    "23.webp",
    "24.webp",
    "25.webp",
    "26.webp",
    "27.webp",
    "28.webp",
    "29.webp",
    "30.webp",
    "31.webp",
    "32.webp",
    "33.webp",
    "34.webp",
    "35.webp",
    "36.webp",
    "37.webp",
    "38.webp",
    "39.webp",
    "40.webp",
    "41.webp",
    "42.webp",
    "43.webp",
    "Stop Trying To Control Everything.webp",
    "Sometimes All You Need Is You.webp",
    "The Boy Billy Butcher.webp",
    "Original Mindset.webp",
    "Dont Be Introverted.webp"
];

export const ARCHIVED_POSTERS = RAW_ARCHIVED_POSTERS.filter(
    (f) => !f.endsWith(".pdf") && !ACTIVE_POSTERS.includes(f)
);
